export const CATEGORIES = [
  { value: 'music', label: 'Музыка' },
  { value: 'gaming', label: 'Видеоигры' },
  { value: 'education', label: 'Образование' },
  { value: 'blogs', label: 'Блоги' },
  { value: 'tech', label: 'Технологии и IT' },
  { value: 'comedy', label: 'Юмор' },
  { value: 'science', label: 'Наука' },
  { value: 'sports', label: 'Спорт' },
  { value: 'movies', label: 'Кино и сериалы' },
  { value: 'lifestyle', label: 'Красота и стиль' },
  { value: 'auto', label: 'Авто и мото' },
  { value: 'travel', label: 'Путешествия' },
  { value: 'cooking', label: 'Кулинария и еда' },
  { value: 'news', label: 'Новости и политика' },
  { value: 'animation', label: 'Анимация и мультфильмы' },
  { value: 'finance', label: 'Бизнес и финансы' },
  { value: 'animals', label: 'Животные' },
] as const;
